Ug encode to sentence piece text
browsermt/marian-dev pull request #13
Opened 2020-12-12 18:01 UTC by ugermann

### Description
add member function to allow encoding/decoding into SentencePieceText.

List of changes:
- adds member function to allow encoding/decoding into SentencePieceText.

### Checklist

- [ ] I have tested the code manually
- [ ] I have run regression tests
- [ ] I have read and followed CONTRIBUTING.md
- [x] I have updated CHANGELOG.md

2020-12-12 18:11 UTC, kpu commented on src/data/vocab_base.h
> +#  include "sentencepiece/src/sentencepiece_processor.h"
So much for abstraction.  The generic vocab class shouldn't need to include sentencepiece.

2020-12-12 18:12 UTC, kpu commented on src/data/vocab_base.h
> +                      sentencepiece::SentencePieceText* /*encoded*/) const {
And it won't ever be because of the wrong class.  Also, now it won't compile without sentencepiece.

2020-12-12 18:13 UTC, kpu requested changes
Bad idea.  Breaks abstraction in a way that could have been preserved.

2021-01-26 14:57 UTC, abhi-agg commented
@ugermann Is this PR still valid?

2021-01-26 15:18 UTC, ugermann commented
No.

2021-01-26 15:18 UTC, closed without merging